name: SFTP Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SSH Deploy
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SFTP_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.SFTP_HOST }}
        REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
        TARGET: ${{ secrets.SFTP_REMOTE_PATH }}
        SOURCE: "/"
        ARGS: "-rlgoDzvc -i --delete"